CREATE VIEW [dbo].[ViewUserList]
	AS 
		SELECT [USER_PID], [USER_NAME], [ROLE_NAME], [TEAM_NAME], [SITE_NAME]
		FROM [DATA_USERS]
		INNER JOIN [LOOKUP_ROLE] ON [LOOKUP_ROLE].[ROLE_ID] = [DATA_USERS].[USER_ROLE]
		INNER JOIN [LOOKUP_TEAM] ON [LOOKUP_TEAM].[TEAM_ID] = [DATA_USERS].[USER_TEAM]
		INNER JOIN [LOOKUP_SITE] ON [LOOKUP_SITE].[SITE_ID] = [DATA_USERS].[USER_SITE]
