CREATE PROCEDURE [dbo].[PopulateTableTimes]

AS
	INSERT INTO 
		[TABLE_TIME] (
			[TIME_KEY], 
			[TIME_TIME], 
			[TIME_NAME]
			)
	SELECT 
		[NUMBER] AS [TIME_KEY], 
		CONVERT(VARCHAR, DATEADD(ms, [NUMBER] * 1000, 0), 114) AS [TIME_TIME], 
		CONVERT(VARCHAR(8),CONVERT(VARCHAR, DATEADD(ms, [NUMBER] * 1000, 0), 114),108) AS [TIME_NAME]
	FROM
		[TABLE_NUMBERS]
	ORDER BY 
		[NUMBER]
	;

RETURN 0
