CREATE PROCEDURE [dbo].[PopulateUserData]

AS
	--DROP TABLE IF EXISTS [#TABLE_1];
	IF OBJECT_ID('tempdb.dbo.[#T_PID]', 'U') IS NOT NULL DROP TABLE [#T_PID];
	IF OBJECT_ID('tempdb.dbo.[#T_NAME]', 'U') IS NOT NULL DROP TABLE [#T_NAME];
	--IF OBJECT_ID('tempdb.dbo.[#T_TEAM]', 'U') IS NOT NULL DROP TABLE [#T_TEAM];
	--IF OBJECT_ID('tempdb.dbo.[#T_SITE]', 'U') IS NOT NULL DROP TABLE [#T_SITE];
	--IF OBJECT_ID('tempdb.dbo.[#T_ROLE]', 'U') IS NOT NULL DROP TABLE [#T_ROLE];

	CREATE TABLE [#T_PID] (
		[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
		[PID] INT NOT NULL,
		);

	CREATE TABLE [#T_NAME] (
		[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
		[FULLNAME] VARCHAR(50) NOT NULL,
		);

	WITH [RANDOM_PIDS] AS (
		SELECT 1 ID,CAST(RAND(CHECKSUM(NEWID()))*8888888 AS INT) +1000000 AS [PID]
		UNION  ALL
		SELECT ID + 1,CAST(RAND(CHECKSUM(NEWID()))*8888888 AS INT)  +1000000 AS [PID]
		FROM [RANDOM_PIDS]
		WHERE 
		ID < 25
		)
	INSERT INTO [#T_PID] ([PID])
	SELECT [PID]
	FROM [RANDOM_PIDS]
	OPTION (MAXRECURSION 0);

	WITH [RANDOM_NAMES] AS (
		SELECT * FROM (VALUES ('Agatha'),('Logan'),('Dania'),('Ken'),('Alex')) [T1] ([FIRST])
		CROSS JOIN (VALUES ('Christie'),('Raisin'),('McRae'),('Stott'),('Rebus')) [T2] ([SURNAME])
		)
	INSERT INTO [#T_NAME] ([FULLNAME])
	SELECT CONCAT([SURNAME],', ', [FIRST]) AS [FULLNAME]
	FROM [RANDOM_NAMES]
	OPTION (MAXRECURSION 0)

	SELECT * 
	FROM #T_PID
	INNER JOIN [#T_NAME] ON [#T_PID].[ID] = [#T_NAME].[ID]
RETURN 0
