CREATE TABLE [ExPat].[Employers] (
    [EmployerID]                INT           IDENTITY (-1, 1) NOT NULL,
    [PAYERef]                   VARCHAR (50)  NOT NULL,
    [EmployerName]              VARCHAR (50)  NOT NULL,
    [ParentGroupID]             INT           NOT NULL,
    [IsParent]                  BIT           DEFAULT ((0)) NOT NULL,
    [EntityID]                  INT           NOT NULL,
    [CountryID]                 INT           NOT NULL,
    [COTAXUTR]                  VARCHAR (50)  NOT NULL,
    [CustomerGroupID]           INT           NOT NULL,
    [IndustrySectorID]          INT           NOT NULL,
    [DedicatedScheme]           BIT           NULL,
    [Appendix4]                 DATE          NULL,
    [Appendix5]                 DATE          NULL,
    [Appendix6]                 DATE          NULL,
    [Appendix7A]                DATE          NULL,
    [Appendix7B]                DATE          NULL,
    [Appendix8]                 DATE          NULL,
    [NonResidentDirector]       BIT           NULL,
    [ConcessionaryCashBasis]    DATE          NULL,
    [BespokeScaleRateAgreement] DATE          NULL,
    [S690]                      DATE          NULL,
    [Notes]                     VARCHAR (250) NULL,
    [ActiveScheme]              BIT           NULL,
    [UpdatedBy]                 INT           NOT NULL,
    [DateUpdated]               DATE          NOT NULL,
    PRIMARY KEY CLUSTERED ([EmployerID] ASC),
    CONSTRAINT [FK_Employers_to_Country] FOREIGN KEY ([CountryID]) REFERENCES [lst].[Country] ([CountryID]),
    CONSTRAINT [FK_Employers_to_CustomerGroup] FOREIGN KEY ([CustomerGroupID]) REFERENCES [lst].[CustomerGroup] ([CustomerGroupID]),
    CONSTRAINT [FK_Employers_to_Entity] FOREIGN KEY ([EntityID]) REFERENCES [lst].[Entity] ([EntityID]),
    CONSTRAINT [FK_Employers_to_IndustrySector] FOREIGN KEY ([IndustrySectorID]) REFERENCES [lst].[IndustrySector] ([IndustrySectorID]),
    CONSTRAINT [FK_Employers_to_ParentGroup] FOREIGN KEY ([ParentGroupID]) REFERENCES [ExPat].[Employers] ([EmployerID])
);

