CREATE TABLE [dbo].[DATA_USERS]
(
    [USER_PID] INT NOT NULL, 
    [USER_NAME] VARCHAR(50) NOT NULL, 
    [USER_TEAM] INT NOT NULL,
    [USER_SITE] INT NOT NULL,
    [USER_ROLE] INT NOT NULL,
    PRIMARY KEY ([USER_PID]), 
    CONSTRAINT [FK_DATA_USERS_to_LOOKUP_TEAM] FOREIGN KEY ([USER_TEAM]) REFERENCES [LOOKUP_TEAM]([TEAM_ID]),
    CONSTRAINT [FK_DATA_USERS_to_LOOKUP_SITE] FOREIGN KEY ([USER_SITE]) REFERENCES [LOOKUP_SITE]([SITE_ID]),
    CONSTRAINT [FK_DATA_USERS_to_LOOKUP_ROLE] FOREIGN KEY ([USER_ROLE]) REFERENCES [LOOKUP_ROLE]([ROLE_ID])
)
