CREATE TABLE [dbo].[LOOKUP_ROLE]
(
	[ROLE_ID] INT NOT NULL IDENTITY(-1,1) PRIMARY KEY, 
    [ROLE_NAME] VARCHAR(50) NOT NULL,
	[ROLE_ACTIVE] BIT NOT NULL, 
    CONSTRAINT [CK_LOOKUP_ROLE_ROLE_NAME] UNIQUE ([ROLE_ID], [ROLE_NAME])
)
