CREATE TABLE [dbo].[TABLE_TIME]
(
	[TIME_KEY] [int] NOT NULL,
	[TIME_TIME] [time](0) NOT NULL,
	[TIME_NAME] [varchar](8) NOT NULL,
 CONSTRAINT [PK_TIME_TABLE] PRIMARY KEY CLUSTERED 
(
	[TIME_KEY] ASC
)
) ON [PRIMARY]
